#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh"  # Loads all defined icons

ITEM_DIR="$CONFIG_DIR/items"            # Directory where the items are configured
export PLUGIN_DIR="$CONFIG_DIR/mm_plugins" # Directory where all the plugin scripts are stored
export PLUGIN_SHARED_DIR="$CONFIG_DIR/shared_plugins"

FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDINGS=3    # All paddings use this value (icon, label, background)

# Setting up the general bar appearance of the bar
bar=(
	height=40
	color=$BAR_COLOR
	shadow=on
	position=top
	sticky=onª≥≥≥≥
	padding_right=10
	padding_left=10
	corner_radius=12 
	y_offset=0
	margin=10
	blur_radius=20
)

sketchybar --bar "${bar[@]}"

# Setting up default values¿
defaults=(
	updates=when_shown
	icon.font="$FONT:Bold:14.0"
	icon.color="$ICON_COLOR"
	icon.padding_left="$PADDINGS"
	icon.padding_right="$PADDINGS"
	label.font="$FONT:Semibold:13.0"
	label.color="$LABEL_COLOR"
	label.padding_left="$PADDINGS"
	label.padding_right="$PADDINGS"
	padding_right="$PADDINGS"
	padding_left="$PADDINGS"
	background.height=30
	background.corner_radius=9
	popup.background.border_width=2
	popup.background.corner_radius=9
	popup.background.border_color="$POPUP_BORDER_COLOR"
	popup.background.color="$POPUP_BACKGROUND_COLOR"
	popup.blur_radius=20
	popup.background.shadow.drawing=on
	scroll_texts=on
)

sketchybar --default "${defaults[@]}"

# Add Music Item
sketchybar -m --add item music right                        \
    --set music script="$PLUGIN_SHARED_DIR/music.sh"        \
    click_script="$PLUGIN_SHARED_DIR/music_click.sh"        \
    label.padding_right=10                                  \
    drawing=off                                             \
    --subscribe music song_update                           \
    scroll_texts=true                                       \
    label.max_chars = 30                                    

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/battery.sh"


# Right
source "$ITEM_DIR/datetime.sh"
source "$ITEM_DIR/music.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/volume.sh"

#sketchybar --hotload off

##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
