#!/usr/bin/env zsh

CONFIG_DIR="$HOME/.config/sketchybar"

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh"  # Loads all defined icons

ITEM_DIR="$CONFIG_DIR/items"            # Directory where the items are configured
PLUGIN_DIR="$CONFIG_DIR/plugins_macloliair" 		# Directory where all the plugin scripts are stored
SHARED_PLUGIN_DIR="$CONFIG_DIR/plugins" 		# Directory where all the plugin scripts are stored

FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDINGS=3    # All paddings use this value (icon, label, background)

# aerospace setting
AEROSPACE_FOCUSED_MONITOR_NO=$(aerospace list-workspaces --focused)
AEROSPACE_LIST_OF_WINDOWS_IN_FOCUSED_MONITOR=$(aerospace list-windows --workspace $AEROSPACE_FOCUSED_MONITOR_NO | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')

# Setting up the general bar appearance of the bar
bar=(
	color=$BAR_COLOR
	height=40
	position=top
	margin=10
	y_offset=0
	corner_radius=12 
	blur_radius=20
	padding_left=10
	padding_right=10
	sticky=on
	shadow=on
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
	updates=when_shown
	icon.font="$FONT:Bold:14.0"
	icon.color="$ICON_COLOR"
	icon.padding_left="$PADDINGS"
	icon.padding_right="$PADDINGS"
	label.font="$FONT:Semibold:13.0"
	label.color="$LABEL_COLOR"
	label.padding_left="$PADDINGS"
	label.padding_right="$PADDINGS"
	padding_right="$PADDINGS"
	padding_left="$PADDINGS"
	background.height=30
	background.corner_radius=9
	popup.background.border_width=2
	popup.background.corner_radius=9
	popup.background.border_color="$POPUP_BORDER_COLOR"
	popup.background.color="$POPUP_BACKGROUND_COLOR"
	popup.blur_radius=20
	popup.background.shadow.drawing=on
	scroll_texts=on
)

sketchybar --default "${defaults[@]}"

# Left
source "$ITEM_DIR/apple.sh"

# Right
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/brew.sh"
source "$ITEM_DIR/input_source.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/music.sh"

sketchybar --hotload on

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update